kind = "web"
previewPath = "/"
title = "Dordle"
version = "1.0.0"
id = "artifacts/dordle"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22652

[services.development]
run = "pnpm --filter @workspace/dordle run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/dordle", "run", "build" ]
publicDir = "artifacts/dordle/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22652"
BASE_PATH = "/"
